# just give command like this $docker run -d --name redis --network roboshop redis:7
# becasue manam redis nimdi data yemi load cheayatam ledu yendhuloki.. just manam install chestunnam redis ante. 

# 3.89.29.234 | 172.31.23.137 | t3.medium | https://github.com/KalyanTalabothula/docker-practice.git
# [ ec2-user@ip-172-31-23-137 ~/docker-practice/rabbitmq ]$ docker pull rabbitmq:3
