# just give command like this $docker run -d --name redis --network roboshop redis:7
# becasue manam redis nimdi data yemi load cheayatam ledu yendhuloki.. just manam install chestunnam redis ante. 

#3.89.29.234 | 172.31.23.137 | t3.medium | https://github.com/KalyanTalabothula/docker-practice.git

# [ ec2-user@ip-172-31-23-137 ~/docker-practice/redis ]$ docker pull redis:7.0

# 🧠 Key Points

# Official Redis images are on Docker Hub: https://hub.docker.com/_/redis

# You cannot use redis:v1 unless you built and tagged it yourself:

# docker pull redis:7.0
# docker tag redis:7.0 redis:v1  # optional, if you really want redis:v1


# Best practice: just use the official tag (redis:7.0) in your docker run command.